services:
  panel:
    environment:
      SG_GATEWAY_ENV: development
      SG_GATEWAY_DATA_DIR: /app/data
      SG_GATEWAY_LOG_DIR: /app/logs
    read_only: false
    volumes:
      - .:/app
    ports:
      - "127.0.0.1:8080:8080"
    command:
      [
        "waitress-serve",
        "--host=0.0.0.0",
        "--port=8080",
        "app.main:app",
      ]