#!/usr/bin/env bash
set -Eeuo pipefail

PREFIX="/opt/sg-gateway"
CONFIG_DIR="/etc/sg-gateway"
DATA_DIR="/var/lib/sg-gateway"
LOG_DIR="/var/log/sg-gateway"
BACKUP_ROOT="/root/sg-gateway-backups"

PANEL_PORT="63443"
XRAY_PORT="443"
AWG_PORT="585"
MIHOMO_PORT="2099"
XHTTP_REALITY_PORT="8444"
XHTTP_TLS_PORT="8445"
HYSTERIA2_PORT="8446"
ANYTLS_PORT="9443"
TUIC_PORT="10443"

XRAY_INSTALLED_BY_SG="0"
AWG_INSTALLED_BY_SG="0"
MIHOMO_INSTALLED_BY_SG="0"
SINGBOX_INSTALLED_BY_SG="0"
SG_INSTALL_PRESENT="0"
SUCCESS="0"
TOTAL_STAGES=6
UNINSTALL_LOG=""

GREEN=$'\033[1;32m'
RED=$'\033[1;31m'
YELLOW=$'\033[1;33m'
CYAN=$'\033[1;36m'
RESET=$'\033[0m'

fail() {
  printf '%s[SG-Gateway] ERROR:%s %s\n' "$RED" "$RESET" "$*" >&2
  exit 1
}

finish() {
  local rc=$?
  if [[ "$SUCCESS" == "1" ]]; then
    [[ -n "$UNINSTALL_LOG" ]] && rm -f "$UNINSTALL_LOG"
  elif [[ -n "$UNINSTALL_LOG" && -f "$UNINSTALL_LOG" ]]; then
    printf '%s[SG-Gateway] Uninstall log preserved:%s %s\n' "$YELLOW" "$RESET" "$UNINSTALL_LOG" >&2
  fi
  exit "$rc"
}
trap finish EXIT
trap 'exit 130' INT TERM

[[ "$(id -u)" -eq 0 ]] || fail "run this uninstaller through sudo"
cd /

if [[ -d "$PREFIX" || -d "$CONFIG_DIR" || -d "$DATA_DIR" \
   || -f /etc/systemd/system/sg-gateway.service ]]; then
  SG_INSTALL_PRESENT="1"
fi

if [[ -f "$CONFIG_DIR/runtime.env" ]]; then
  # This file is generated by SG-Gateway and contains simple shell values.
  # shellcheck disable=SC1090
  source "$CONFIG_DIR/runtime.env"
  PANEL_PORT="${SG_GATEWAY_PANEL_PORT:-$PANEL_PORT}"
  XRAY_PORT="${SG_GATEWAY_XRAY_PORT:-$XRAY_PORT}"
  AWG_PORT="${SG_GATEWAY_AWG_PORT:-$AWG_PORT}"
  MIHOMO_PORT="${SG_GATEWAY_MIHOMO_PORT:-$MIHOMO_PORT}"
  XRAY_INSTALLED_BY_SG="${SG_GATEWAY_XRAY_INSTALLED_BY_SG:-$SG_INSTALL_PRESENT}"
  AWG_INSTALLED_BY_SG="${SG_GATEWAY_AWG_INSTALLED_BY_SG:-$SG_INSTALL_PRESENT}"
  MIHOMO_INSTALLED_BY_SG="${SG_GATEWAY_MIHOMO_INSTALLED_BY_SG:-$SG_INSTALL_PRESENT}"
  SINGBOX_INSTALLED_BY_SG="${SG_GATEWAY_SINGBOX_INSTALLED_BY_SG:-$SG_INSTALL_PRESENT}"
else
  XRAY_INSTALLED_BY_SG="$SG_INSTALL_PRESENT"
  AWG_INSTALLED_BY_SG="$SG_INSTALL_PRESENT"
  MIHOMO_INSTALLED_BY_SG="$SG_INSTALL_PRESENT"
  SINGBOX_INSTALLED_BY_SG="$SG_INSTALL_PRESENT"
fi

printf '\n%sFull SG-Gateway removal%s\n' "$CYAN" "$RESET"
printf 'This removes SG-Gateway application files, databases, backups, services,\n'
printf 'managed engine runtimes, firewall rules and SG-Gateway Nginx configuration.\n'
printf 'Generic Ubuntu packages such as Nginx, Certbot and Python are kept.\n\n'

CONFIRM="${SG_GATEWAY_UNINSTALL_CONFIRM:-}"
if [[ "$CONFIRM" != "DELETE SG-GATEWAY" ]]; then
  [[ -r /dev/tty ]] || fail "interactive terminal is required for confirmation"
  read -r -p "Type DELETE SG-GATEWAY to continue: " CONFIRM < /dev/tty
fi
if [[ "$CONFIRM" != "DELETE SG-GATEWAY" ]]; then
  echo "Removal cancelled."
  SUCCESS="1"
  exit 0
fi

UNINSTALL_LOG="$(mktemp /tmp/sg-gateway-uninstall.XXXXXX.log)"
chmod 0600 "$UNINSTALL_LOG"

run_stage() {
  local stage="$1"
  local label="$2"
  local function_name="$3"
  local started=$SECONDS

  printf '%s[SG-Gateway] [%s/%s]%s %s...\n' \
    "$CYAN" "$stage" "$TOTAL_STAGES" "$RESET" "$label"

  if "$function_name" >> "$UNINSTALL_LOG" 2>&1; then
    printf '%s[SG-Gateway] [OK]%s %s (%s sec.)\n' \
      "$GREEN" "$RESET" "$label" "$((SECONDS - started))"
    return 0
  fi

  printf '%s[SG-Gateway] [FAILED]%s %s\n' "$RED" "$RESET" "$label" >&2
  tail -n 80 "$UNINSTALL_LOG" >&2 || true
  return 1
}

stop_services_and_interfaces() {
  local service
  for service in \
    sg-gateway.service \
    sg-hostd.service \
    sg-gateway-awg.service \
    sg-gateway-singbox.service \
    mihomo.service \
    xray.service \
    xray@.service \
    sing-box.service; do
    systemctl disable --now "$service" >/dev/null 2>&1 || true
  done

  if command -v awg-quick >/dev/null 2>&1; then
    awg-quick down /etc/amnezia/amneziawg/awg0.conf >/dev/null 2>&1 || true
  fi
  if command -v ip >/dev/null 2>&1 && ip link show awg0 >/dev/null 2>&1; then
    ip link delete awg0 >/dev/null 2>&1 || true
  fi
}

remove_network_and_nginx() {
  local rule
  if command -v ufw >/dev/null 2>&1 \
     && ufw status 2>/dev/null | grep -q '^Status: active'; then
    for rule in \
      "${PANEL_PORT}/tcp" \
      "80/tcp" \
      "${XRAY_PORT}/tcp" \
      "${XHTTP_REALITY_PORT}/tcp" \
      "${XHTTP_TLS_PORT}/tcp" \
      "${AWG_PORT}/udp" \
      "${HYSTERIA2_PORT}/udp" \
      "${MIHOMO_PORT}/tcp" \
      "${ANYTLS_PORT}/tcp" \
      "${TUIC_PORT}/udp"; do
      ufw --force delete allow "$rule" >/dev/null 2>&1 || true
    done
  fi

  rm -f \
    /etc/nginx/sites-enabled/sg-gateway \
    /etc/nginx/sites-available/sg-gateway \
    /etc/nginx/sites-enabled/sg-gateway-acme \
    /etc/nginx/sites-available/sg-gateway-acme \
    /etc/letsencrypt/renewal-hooks/deploy/sg-gateway-nginx \
    /etc/letsencrypt/renewal-hooks/deploy/reload-sg-gateway-nginx.sh
  rm -rf /var/www/sg-gateway-acme

  if [[ -d /etc/nginx/sites-enabled \
     && -f /etc/nginx/sites-available/default \
     && -z "$(find /etc/nginx/sites-enabled -mindepth 1 -maxdepth 1 -print -quit 2>/dev/null)" ]]; then
    ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
  fi

  if command -v nginx >/dev/null 2>&1 && nginx -t >/dev/null 2>&1; then
    if systemctl is-active --quiet nginx.service; then
      systemctl reload nginx.service >/dev/null 2>&1 || true
    fi
  fi

  rm -f /etc/sysctl.d/99-sg-gateway.conf
  if command -v sysctl >/dev/null 2>&1; then
    sysctl --system >/dev/null 2>&1 || true
  fi
}

purge_managed_engine_packages() {
  export DEBIAN_FRONTEND=noninteractive
  local apt_changed="0"
  local source_file package
  local -a packages=()

  if [[ "$SINGBOX_INSTALLED_BY_SG" == "1" ]] \
     && dpkg-query -W -f='${Status}' sing-box 2>/dev/null | grep -q 'install ok installed'; then
    packages+=(sing-box)
  fi

  if [[ "$AWG_INSTALLED_BY_SG" == "1" ]]; then
    for package in amneziawg amneziawg-dkms amneziawg-tools; do
      if dpkg-query -W -f='${Status}' "$package" 2>/dev/null | grep -q 'install ok installed'; then
        packages+=("$package")
      fi
    done
  fi

  if (( ${#packages[@]} > 0 )); then
    apt-get -o Dpkg::Use-Pty=0 purge -y "${packages[@]}" || {
      for package in "${packages[@]}"; do
        dpkg --purge "$package" >/dev/null 2>&1 || true
      done
    }
    apt_changed="1"
  fi

  rm -f \
    /etc/apt/sources.list.d/sagernet.sources \
    /etc/apt/keyrings/sagernet.asc

  if [[ "$AWG_INSTALLED_BY_SG" == "1" && -d /etc/apt/sources.list.d ]]; then
    while IFS= read -r -d '' source_file; do
      if grep -Eqs 'ppa\.launchpad(content)?\.net/amnezia/ppa|ppa:amnezia/ppa' "$source_file"; then
        rm -f "$source_file"
      fi
    done < <(find /etc/apt/sources.list.d -maxdepth 1 -type f -print0)
    find /etc/apt/keyrings /etc/apt/trusted.gpg.d -maxdepth 1 -type f \
      -iname '*amnezia*' -delete 2>/dev/null || true
  fi

  if [[ "$apt_changed" == "1" ]]; then
    apt-get -o Dpkg::Use-Pty=0 autoremove -y >/dev/null 2>&1 || true
  fi
}

remove_units_and_runtimes() {
  rm -rf \
    /etc/systemd/system/sg-gateway.service.d \
    /etc/systemd/system/sg-hostd.service.d \
    /etc/systemd/system/xray.service.d \
    /etc/systemd/system/xray@.service.d

  rm -f \
    /etc/systemd/system/sg-gateway.service \
    /etc/systemd/system/sg-hostd.service \
    /etc/systemd/system/sg-gateway-awg.service \
    /etc/systemd/system/sg-gateway-singbox.service \
    /etc/systemd/system/mihomo.service

  if [[ "$XRAY_INSTALLED_BY_SG" == "1" ]]; then
    rm -rf \
      /usr/local/etc/xray \
      /usr/local/share/xray \
      /var/log/xray \
      /etc/systemd/system/xray.service.d \
      /etc/systemd/system/xray@.service.d
    rm -f \
      /usr/local/bin/xray \
      /etc/systemd/system/xray.service \
      /etc/systemd/system/xray@.service
  fi

  if [[ "$MIHOMO_INSTALLED_BY_SG" == "1" ]]; then
    rm -f /usr/local/bin/mihomo
    rm -rf /etc/mihomo /var/lib/mihomo /var/log/mihomo
  fi

  if [[ "$SINGBOX_INSTALLED_BY_SG" == "1" ]]; then
    rm -rf /etc/sing-box /var/lib/sing-box /var/log/sing-box
    rm -f \
      /usr/local/bin/sing-box \
      /etc/systemd/system/sing-box.service \
      /usr/lib/systemd/system/sing-box.service \
      /lib/systemd/system/sing-box.service
  fi

  rm -f /usr/local/bin/wgcf-cli
  rm -rf /etc/amnezia/amneziawg /run/sg-gateway

  systemctl daemon-reload
  systemctl reset-failed >/dev/null 2>&1 || true
}

remove_application_and_legacy_files() {
  if command -v docker >/dev/null 2>&1; then
    if [[ -f "$PREFIX/docker-compose.yml" ]] \
       && docker compose version >/dev/null 2>&1; then
      (
        cd "$PREFIX"
        docker compose down --volumes --remove-orphans || true
      )
    fi
    docker rm -f sg-gateway-panel sg-gateway-xray >/dev/null 2>&1 || true
    docker volume rm \
      sg-gateway_sg_gateway_data \
      sg-gateway_sg_gateway_logs \
      sg-gateway_sg_gateway_xray \
      sg_gateway_data \
      sg_gateway_logs \
      sg_gateway_xray >/dev/null 2>&1 || true
  fi

  rm -rf \
    "$PREFIX" \
    "$CONFIG_DIR" \
    "$DATA_DIR" \
    "$LOG_DIR" \
    "$BACKUP_ROOT"

  rm -f \
    /var/log/sg-gateway-installer*.log \
    /var/log/sg-gateway-uninstall*.log \
    /root/sg-gateway-*-installer-resume.env \
    /root/sg-gateway-preview*-installer-resume.env

  if id sg-gateway >/dev/null 2>&1; then
    userdel sg-gateway >/dev/null 2>&1 || true
  fi
  if getent group sg-gateway >/dev/null 2>&1; then
    groupdel sg-gateway >/dev/null 2>&1 || true
  fi
}

verify_removal() {
  local -a leftovers=()
  local path service package

  for path in \
    "$PREFIX" \
    "$CONFIG_DIR" \
    "$DATA_DIR" \
    "$LOG_DIR" \
    "$BACKUP_ROOT" \
    /etc/systemd/system/sg-gateway.service \
    /etc/systemd/system/sg-hostd.service \
    /etc/systemd/system/sg-gateway-awg.service \
    /etc/systemd/system/sg-gateway-singbox.service \
    /etc/systemd/system/mihomo.service \
    /etc/nginx/sites-available/sg-gateway \
    /etc/nginx/sites-enabled/sg-gateway \
    /etc/nginx/sites-available/sg-gateway-acme \
    /etc/nginx/sites-enabled/sg-gateway-acme \
    /etc/letsencrypt/renewal-hooks/deploy/reload-sg-gateway-nginx.sh \
    /etc/sysctl.d/99-sg-gateway.conf \
    /etc/amnezia/amneziawg \
    /usr/local/bin/wgcf-cli; do
    if [[ -e "$path" || -L "$path" ]]; then
      leftovers+=("path:$path")
    fi
  done

  if [[ "$XRAY_INSTALLED_BY_SG" == "1" ]]; then
    for path in /usr/local/bin/xray /usr/local/etc/xray /usr/local/share/xray; do
      [[ -e "$path" || -L "$path" ]] && leftovers+=("path:$path")
    done
  fi
  if [[ "$MIHOMO_INSTALLED_BY_SG" == "1" ]]; then
    for path in /usr/local/bin/mihomo /etc/mihomo /var/lib/mihomo; do
      [[ -e "$path" || -L "$path" ]] && leftovers+=("path:$path")
    done
  fi
  if [[ "$SINGBOX_INSTALLED_BY_SG" == "1" ]]; then
    for path in /etc/sing-box /var/lib/sing-box /var/log/sing-box; do
      [[ -e "$path" || -L "$path" ]] && leftovers+=("path:$path")
    done
  fi

  for service in \
    sg-gateway.service \
    sg-hostd.service \
    sg-gateway-awg.service \
    sg-gateway-singbox.service \
    mihomo.service; do
    if systemctl cat "$service" >/dev/null 2>&1; then
      leftovers+=("service:$service")
    fi
  done
  if [[ "$XRAY_INSTALLED_BY_SG" == "1" ]] \
     && systemctl cat xray.service >/dev/null 2>&1; then
    leftovers+=("service:xray.service")
  fi
  if [[ "$SINGBOX_INSTALLED_BY_SG" == "1" ]] \
     && systemctl cat sing-box.service >/dev/null 2>&1; then
    leftovers+=("service:sing-box.service")
  fi

  if [[ "$SINGBOX_INSTALLED_BY_SG" == "1" ]]; then
    for package in sing-box; do
      if dpkg-query -W -f='${Status}' "$package" 2>/dev/null | grep -q 'install ok installed'; then
        leftovers+=("package:$package")
      fi
    done
  fi
  if [[ "$AWG_INSTALLED_BY_SG" == "1" ]]; then
    for package in amneziawg amneziawg-dkms amneziawg-tools; do
      if dpkg-query -W -f='${Status}' "$package" 2>/dev/null | grep -q 'install ok installed'; then
        leftovers+=("package:$package")
      fi
    done
  fi

  if id sg-gateway >/dev/null 2>&1; then
    leftovers+=("user:sg-gateway")
  fi
  if getent group sg-gateway >/dev/null 2>&1; then
    leftovers+=("group:sg-gateway")
  fi

  if (( ${#leftovers[@]} > 0 )); then
    printf 'SG-Gateway leftovers were found:\n' >&2
    printf '  %s\n' "${leftovers[@]}" >&2
    return 1
  fi
}

run_stage 1 "Stop SG-Gateway services and interfaces" stop_services_and_interfaces
run_stage 2 "Remove firewall, Nginx and sysctl configuration" remove_network_and_nginx
run_stage 3 "Purge SG-managed engine packages and repositories" purge_managed_engine_packages
run_stage 4 "Remove systemd units and engine runtimes" remove_units_and_runtimes
run_stage 5 "Remove application, data, backups and legacy files" remove_application_and_legacy_files
run_stage 6 "Verify complete SG-Gateway removal" verify_removal

SUCCESS="1"
printf '\n%sSG-Gateway has been completely removed.%s\n' "$GREEN" "$RESET"
printf 'No SG-Gateway application, database, backup, service or managed runtime remains.\n'
